-- MySQL Script generated by MySQL Workbench
-- qua 26 nov 2025 08:21:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SIMRD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SIMRD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SIMRD` ;
USE `SIMRD` ;

-- -----------------------------------------------------
-- Table `SIMRD`.`Credes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIMRD`.`Credes` (
  `idCredes` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idCredes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMRD`.`Secretarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIMRD`.`Secretarias` (
  `idSecretarias` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idSecretarias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMRD`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIMRD`.`Status` (
  `idStatus` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMRD`.`Componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIMRD`.`Componente` (
  `idComponente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idComponente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMRD`.`Serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIMRD`.`Serie` (
  `idSerie` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idSerie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMRD`.`Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIMRD`.`Tarefa` (
  `idTarefa` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `responsavel` VARCHAR(45) NULL,
  `componente` INT NULL,
  `serie` INT NULL,
  `status` INT NULL,
  `data_inicial` DATETIME NULL,
  `data_final` DATETIME NULL,
  PRIMARY KEY (`idTarefa`),
  INDEX `fk_Tarefa_Status_idx` (`status` ASC) VISIBLE,
  INDEX `fk_Tarefa_Componente_idx` (`componente` ASC) VISIBLE,
  INDEX `fk_Tarefa_Serie_idx` (`serie` ASC) VISIBLE,
  CONSTRAINT `fk_Tarefa_Status`
    FOREIGN KEY (`status`)
    REFERENCES `SIMRD`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tarefa_Componente`
    FOREIGN KEY (`componente`)
    REFERENCES `SIMRD`.`Componente` (`idComponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tarefa_Serie`
    FOREIGN KEY (`serie`)
    REFERENCES `SIMRD`.`Serie` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMRD`.`Ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIMRD`.`Ciclo` (
  `idCiclo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idCiclo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMRD`.`Avaliacao_formativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIMRD`.`Avaliacao_formativa` (
  `idAvaliacao_formativa` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idAvaliacao_formativa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMRD`.`Planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIMRD`.`Planos` (
  `idPlanos` INT NOT NULL,
  `previstos` VARCHAR(45) NULL,
  `defasagem` VARCHAR(45) NULL,
  `avaliados` VARCHAR(45) NULL,
  `reducao` VARCHAR(45) NULL,
  `status` INT NULL,
  `avaliacao` INT NULL,
  `ciclo` INT NULL,
  `componente` INT NULL,
  `serie` INT NULL,
  PRIMARY KEY (`idPlanos`),
  INDEX `fk_Planos_Ciclo_idx` (`ciclo` ASC) VISIBLE,
  INDEX `fk_Planos_Avaliacao_idx` (`avaliacao` ASC) VISIBLE,
  INDEX `fk_Planos_Componente_idx` (`componente` ASC) VISIBLE,
  INDEX `fk_Planos_Serie_idx` (`serie` ASC) VISIBLE,
  CONSTRAINT `fk_Planos_Status`
    FOREIGN KEY ()
    REFERENCES `SIMRD`.`Status` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planos_Ciclo`
    FOREIGN KEY (`ciclo`)
    REFERENCES `SIMRD`.`Ciclo` (`idCiclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planos_Avaliacao`
    FOREIGN KEY (`avaliacao`)
    REFERENCES `SIMRD`.`Avaliacao_formativa` (`idAvaliacao_formativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planos_Serie`
    FOREIGN KEY (`serie`)
    REFERENCES `SIMRD`.`Serie` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planos_Componente`
    FOREIGN KEY (`componente`)
    REFERENCES `SIMRD`.`Componente` (`idComponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMRD`.`Escolas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIMRD`.`Escolas` (
  `idEscolas` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `inep` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `localidade` VARCHAR(45) NULL,
  `tarefa` INT NULL,
  `planos` INT NULL,
  PRIMARY KEY (`idEscolas`),
  INDEX `fk_Escolas_Tarefa_idx` (`tarefa` ASC) VISIBLE,
  INDEX `fk_Escolas_Planos_idx` (`planos` ASC) VISIBLE,
  CONSTRAINT `fk_Escolas_Tarefa`
    FOREIGN KEY (`tarefa`)
    REFERENCES `SIMRD`.`Tarefa` (`idTarefa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Escolas_Planos`
    FOREIGN KEY (`planos`)
    REFERENCES `SIMRD`.`Planos` (`idPlanos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
